# Generated by Django 4.2.7 on 2023-11-13 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProductInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('number', models.CharField(max_length=300)),
                ('operation', models.CharField(choices=[('option_1', 'Покупка, комісія'), ('option_2', "Об'єкти будівництва"), ('option_2', 'У переробку')], max_length=300)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=300)),
                ('contractor', models.CharField(max_length=300)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_number', models.CharField(max_length=300, null=True)),
                ('contract', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProductOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('number', models.CharField(max_length=300)),
                ('operation', models.CharField(max_length=300)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=300)),
                ('storage', models.CharField(max_length=300)),
                ('organization', models.CharField(max_length=300)),
                ('accountable', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('units', models.CharField(max_length=300)),
                ('coefficient', models.DecimalField(decimal_places=3, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bill', models.IntegerField()),
                ('sub_account', models.CharField(max_length=300)),
            ],
        ),
    ]
