# Generated by Django 4.2.7 on 2023-11-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document_product_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_manager.documentproductinput'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_product_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_manager.documentproductoutput'),
        ),
        migrations.AddField(
            model_name='service',
            name='document_service_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='product_manager.documentproductinput'),
        ),
        migrations.AddField(
            model_name='service',
            name='document_service_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='product_manager.documentproductoutput'),
        ),
    ]
