# Generated by Django 4.2.7 on 2023-11-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_product_document_product_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproductinput',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentproductinput',
            name='entry_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_product_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_manager.documentproductinput'),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_product_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_manager.documentproductoutput'),
        ),
        migrations.AlterField(
            model_name='service',
            name='document_service_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='product_manager.documentproductinput'),
        ),
        migrations.AlterField(
            model_name='service',
            name='document_service_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='product_manager.documentproductoutput'),
        ),
    ]
