# Generated by Django 4.2.7 on 2023-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_alter_documentproductinput_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
