# Generated by Django 4.2.7 on 2023-11-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0005_serviceinput_serviceoutput_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentProductInput',
            new_name='DocumentInput',
        ),
        migrations.RenameModel(
            old_name='DocumentProductOutput',
            new_name='DocumentOutput',
        ),
    ]
