# Generated by Django 4.2.7 on 2023-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0006_rename_documentproductinput_documentinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinput',
            name='storage',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentoutput',
            name='storage',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
