# Generated by Django 4.2.7 on 2023-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0008_rename_sub_account_serviceoutput_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoutput',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='serviceoutput',
            name='bill',
            field=models.IntegerField(null=True),
        ),
    ]
