# Generated by Django 4.2.7 on 2023-11-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0009_remove_serviceoutput_tax_rate_serviceoutput_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_index',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
