# Generated by Django 4.2.7 on 2023-12-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0011_alter_product_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='documentinput',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_input', to='product_manager.storage'),
        ),
        migrations.AlterField(
            model_name='documentoutput',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_output', to='product_manager.storage'),
        ),
    ]
