# Generated by Django 4.2.7 on 2023-12-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0012_storage_alter_documentinput_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinput',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='documentoutput',
            name='sum',
        ),
    ]
