# Generated by Django 4.2.7 on 2023-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0013_remove_documentinput_sum_remove_documentoutput_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinput',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='documentoutput',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
