# Generated by Django 4.2.7 on 2023-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0014_documentinput_sum_documentoutput_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinput',
            name='operation',
            field=models.CharField(choices=[('Покупка, комісія', 'Покупка, комісія'), ("Об'єкти будівництва", "Об'єкти будівництва"), ('У переробку', 'У переробку')], max_length=300),
        ),
    ]
